name: stepathlon
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

flutter_intl:
  main_locale: en
  enabled: true

dependencies:
  beamer: ^1.5.3
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  dio: ^5.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_form_builder: ^7.8.0
  flutter_localizations:
    sdk: flutter
  flutter_loggy: ^2.0.2
  flutter_loggy_dio: ^3.0.1
  form_builder_validators: ^8.5.0
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.3.4
  intl: ^0.17.0
  json_annotation: ^4.8.0
  loggy: ^2.0.3
  q_architecture:
    git:
      url: https://oauth2:glpat-oW4hmybcy68HdpWC73NR@gitlab.qagency.io/mobile/flutter_packages/q_flutter_starter.git
      ref: master
      path: q_architecture
  retrofit: ^4.0.1
  reusable_widgets_docs_generator:
    git:
      url: https://oauth2:glpat-oW4hmybcy68HdpWC73NR@gitlab.qagency.io/flutter/reusable-widget-generator.git
      ref: master
  sentry_flutter: ^7.4.1
  shake: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.7.2
  flutter_flavorizr: ^2.1.6
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  mocktail: ^0.3.0
  retrofit_generator: null
  state_notifier_test: ^0.0.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/

